---
- name: Create an empty text file
  hosts: all
  become: true
  tasks:
    - name: Create the empty text file
      file:
        path: /home/fcpo/ansible_test/empty.txt
        state: touch
        owner: fcpo
        group: fcpo
        mode: '0777'
